// Generated by Wrangler on Mon Aug 26 2024 04:34:13 GMT+0900 (Japan Standard Time)
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
	DATA: R2Bucket;
	DB: D1Database;
}
