#:schema node_modules/wrangler/config-schema.json
name = "imgin"
compatibility_date = "2024-08-15"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[r2_buckets]]
binding = 'DATA'
bucket_name = 'imgin-data'

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "imgin-db"
database_id = "63f56a4c-befb-4b93-9512-a3030c04a96b"
